INSERT INTO TESTE_USUARIO (ID, NOME, EMAIL, LOGIN, SENHA, SITUACAO) VALUES (1, 'Root', 'root@mail.com', 'root', '1234', 'ATIVO');
INSERT INTO TESTE_USUARIO (ID, NOME, EMAIL, LOGIN, SENHA, SITUACAO) VALUES (2, 'User1', 'user1@mail.com', 'users1', 'abcd', 'ATIVO');
INSERT INTO TESTE_USUARIO (ID, NOME, EMAIL, LOGIN, SENHA, SITUACAO) VALUES (3, 'User2', 'user2@mail.com', 'users2', 'efgh', 'ATIVO');
INSERT INTO TESTE_USUARIO (ID, NOME, EMAIL, LOGIN, SENHA, SITUACAO) VALUES (4, 'User3', 'user3@mail.com', 'user3', 'ijkl', 'ATIVO');

INSERT INTO TESTE_PERFIL (ID, DESCRICAO) VALUES (1, 'User');
INSERT INTO TESTE_PERFIL (ID, DESCRICAO) VALUES (2, 'Admin');
INSERT INTO TESTE_PERFIL (ID, DESCRICAO) VALUES (3, 'Guest');

INSERT INTO TESTE_RECURSO (ID, NOME, CHAVE) VALUES (1, 'Tela Usuario', 'usuario');
INSERT INTO TESTE_RECURSO (ID, NOME, CHAVE) VALUES (2, 'Tela Perfil', 'perfil');
INSERT INTO TESTE_RECURSO (ID, NOME, CHAVE) VALUES (3, 'Tela Recurso', 'recurso');
