INSERT INTO TESTE_PERFIL (ID, DESCRICAO) VALUES (1, 'User');
INSERT INTO TESTE_PERFIL (ID, DESCRICAO) VALUES (2, 'Admin');
INSERT INTO TESTE_PERFIL (ID, DESCRICAO) VALUES (3, 'Guest');

INSERT INTO TESTE_RECURSO (ID, NOME, CHAVE) VALUES (1, 'Tela Usuario', 'usuario');
INSERT INTO TESTE_RECURSO (ID, NOME, CHAVE) VALUES (2, 'Tela Perfil', 'perfil');
INSERT INTO TESTE_RECURSO (ID, NOME, CHAVE) VALUES (3, 'Tela Recurso', 'recurso');
